### ISSUE TITLE
ValueError: Cannot parse hostname out of URI 'gateway.discord.gg'

### ISSUE THREAD

**Issue by hysystem** [Bluenix2/discord-gateway#3]
`
import socket
import ssl
import threading
import time
from sys import platform

import certifi
from discord_gateway import DiscordConnection

import socks  # pip install PySocks

TOKEN = '********************************'
RECV_SIZE = 65536
SERVER_NAME = 'gateway.discord.gg'

socks.set_default_proxy(socks.HTTP, "127.0.0.1", 7890)  
socket.socket = socks.socksocket  

def heartbeat(conn, sock):
    while True:
        sock.send(conn.heartbeat())
        time.sleep(conn.heartbeat_interval)

def recv_event(conn, sock):
    while True:
        for event in conn.events():
            return event

        for to_send in conn.receive(sock.recv(RECV_SIZE)):
            sock.send(to_send)

def main():
    # Setup the socket and SSL for the WebSocket Secure connection.
    conn = DiscordConnection(SERVER_NAME, encoding='json')
    ctx = ssl.create_default_context(cafile=certifi.where())

    sock = socket.create_connection(conn.destination)

    sock = ctx.wrap_socket(sock, server_hostname=SERVER_NAME)

    sock.send(conn.connect())  # Convert to a WebSocket

    # Receive the very first HELLO event.
    hello = recv_event(conn, sock)

    # Send RESUME or IDENTIFY depending on state (will always be False
    # when initially connecting, but may be different when reconnecting).
    if conn.should_resume:
        sock.send(conn.resume(TOKEN))
    else:
        sock.send(conn.identify(
            token=TOKEN,
            intents=65535,
            properties={
                '$os': platform,
                '$browser': 'discord-gateway',
                '$device': 'discord-gateway'
            },
        ))

    heartbeater = threading.Thread(target=heartbeat, args=(conn, sock))
    heartbeater.start()

    try:
        while True:
            event = recv_event(conn, sock)
            print('Received:', event)
    finally:
        sock.shutdown(socket.SHUT_WR)
        sock.close()

if __name__ == '__main__':
    main()`

`

Traceback (most recent call last):
  File "F:\code\dc-monitor\dc_websocket.py", line 78, in <module>
    main()
  File "F:\code\dc-monitor\dc_websocket.py", line 41, in main
    sock = socket.create_connection(conn.destination)
                                    ^^^^^^^^^^^^^^^^
  File "F:\code\dc-monitor\venv\Lib\site-packages\discord_gateway\conn.py", line 171, in destination
    raise ValueError(f"Cannot parse hostname out of URI '{self.uri}'")
ValueError: Cannot parse hostname out of URI 'gateway.discord.gg'

**Comment by Bluenix2** [comment]
Hey thanks for catching this. This was previously supported when I was manually parsing the URI, but after switching to `urllib.parse` it appears that this stopped working as it isn't parsed correctly.

I have updated the example which you can see in a8525074a1213637b3e25f5f1a33ec2a2d92c519. For a more complete example, I recommend looking at the implementation here: [`wumpy-gateway`](https://github.com/wumpyproject/wumpy/blob/main/library/wumpy-gateway/wumpy/gateway/_shard.py)!

**Comment by ghost** [comment]
@Bluenix2 isnt ur library the one that also fakes tls fingeprints etc.? if so u should allow specifying which platform we're doing that for otherwise even tokens acquired on linux being treated as win sessions which puts accounts in danger
